// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(KkcsDbContext))]
    [Migration("20260909092541_AddBungaSimpanan")]
    partial class AddBungaSimpanan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Anggota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomorAnggota")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NomorIdentitas")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomorTelepon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("TanggalBergabung")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NomorAnggota")
                        .IsUnique();

                    b.ToTable("Anggota");
                });

            modelBuilder.Entity("AngsuranPinjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AngsuranKe")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DibayarPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jasa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("JatuhTempo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("JumlahDibayar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PinjamanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Pokok")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PinjamanId", "AngsuranKe");

                    b.ToTable("AngsuranPinjaman");
                });

            modelBuilder.Entity("EratAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("MulaiPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SelesaiPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EratAgenda");
                });

            modelBuilder.Entity("EratOpsi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EratAgendaId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Urutan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EratAgendaId");

                    b.ToTable("EratOpsi");
                });

            modelBuilder.Entity("EratSuara", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DipilihPada")
                        .HasColumnType("datetime2");

                    b.Property<int>("EratAgendaId")
                        .HasColumnType("int");

                    b.Property<int>("EratOpsiId")
                        .HasColumnType("int");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EratOpsiId");

                    b.HasIndex("PenggunaId");

                    b.HasIndex("EratAgendaId", "PenggunaId")
                        .IsUnique();

                    b.ToTable("EratSuara");
                });

            modelBuilder.Entity("JenisSimpanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("JenisSimpanan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            Deskripsi = "Simpanan awal keanggotaan.",
                            Kode = "POKOK",
                            Nama = "Simpanan Pokok"
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            Deskripsi = "Simpanan berkala anggota.",
                            Kode = "WAJIB",
                            Nama = "Simpanan Wajib"
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            Deskripsi = "Simpanan tambahan sesuai kemampuan anggota.",
                            Kode = "SUKARELA",
                            Nama = "Simpanan Sukarela"
                        },
                        new
                        {
                            Id = 4,
                            Aktif = true,
                            Deskripsi = "Simpanan dengan jangka waktu tertentu.",
                            Kode = "BERJANGKA",
                            Nama = "Simpanan Berjangka"
                        });
                });

            modelBuilder.Entity("KonfigurasiKoperasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BungaDepositoTahunan")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("BungaSukarelaTahunan")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("DiperbaruiPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SimpananPokokNominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SimpananWajibNominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TanggalTagihWajib")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KonfigurasiKoperasi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BungaDepositoTahunan = 0.045m,
                            BungaSukarelaTahunan = 0.025m,
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SimpananPokokNominal = 100000m,
                            SimpananWajibNominal = 50000m,
                            TanggalTagihWajib = 25
                        });
                });

            modelBuilder.Entity("LaporanTahunan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DiterbitkanPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tahun")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tahun")
                        .IsUnique();

                    b.ToTable("LaporanTahunan");
                });

            modelBuilder.Entity("MutasiSimpanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoSetelah")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SimpananId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TanggalTransaksi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SimpananId");

                    b.ToTable("MutasiSimpanan");
                });

            modelBuilder.Entity("PembayaranPinjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AngsuranKe")
                        .HasColumnType("int");

                    b.Property<string>("Catatan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DiajukanPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiputuskanPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("JasaDibebaskan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("JumlahDiajukan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<int>("PinjamanId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId");

                    b.HasIndex("PinjamanId", "Status");

                    b.ToTable("PembayaranPinjaman");
                });

            modelBuilder.Entity("PengajuanPinjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BungaTahunan")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiputuskanPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimasiCicilanBulanan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimasiTotalJasa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomorPengajuan")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TenorBulan")
                        .HasColumnType("int");

                    b.Property<string>("Tujuan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("NomorPengajuan")
                        .IsUnique();

                    b.HasIndex("PenggunaId");

                    b.ToTable("PengajuanPinjaman");
                });

            modelBuilder.Entity("Pengguna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisetujuiPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomorIndukKaryawan")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NomorTelepon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Peran")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Anggota");

                    b.Property<string>("StatusKeanggotaan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Aktif");

                    b.HasKey("Id");

                    b.HasIndex("NomorIndukKaryawan")
                        .IsUnique();

                    b.ToTable("Pengguna");
                });

            modelBuilder.Entity("Pinjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AngsuranPerBulan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AngsuranTerbayar")
                        .HasColumnType("int");

                    b.Property<decimal>("BungaTahunan")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("JasaPerBulan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("LunasPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomorPinjaman")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PengajuanPinjamanId")
                        .HasColumnType("int");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Pokok")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PokokPerBulan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SisaPokok")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenorBulan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomorPinjaman")
                        .IsUnique();

                    b.HasIndex("PengajuanPinjamanId")
                        .IsUnique();

                    b.HasIndex("PenggunaId");

                    b.ToTable("Pinjaman");
                });

            modelBuilder.Entity("PostingBungaSukarela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DiposkanPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId", "Periode")
                        .IsUnique();

                    b.ToTable("PostingBungaSukarela");
                });

            modelBuilder.Entity("Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DiperbaruiPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Harga")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Satuan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Stok")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("Kode")
                        .IsUnique();

                    b.ToTable("Produk");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktif = true,
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Harga = 78000m,
                            Kode = "PRD-BRSPRM5",
                            Nama = "Beras Premium 5 kg",
                            Satuan = "paket",
                            Stok = 0m
                        },
                        new
                        {
                            Id = 2,
                            Aktif = true,
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Harga = 36500m,
                            Kode = "PRD-MNYK2",
                            Nama = "Minyak Goreng 2 L",
                            Satuan = "botol",
                            Stok = 0m
                        },
                        new
                        {
                            Id = 3,
                            Aktif = true,
                            DiperbaruiPada = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Harga = 17000m,
                            Kode = "PRD-GULA1",
                            Nama = "Gula Pasir 1 kg",
                            Satuan = "paket",
                            Stok = 0m
                        });
                });

            modelBuilder.Entity("ProdukBerjangka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TenorBulan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProdukBerjangka");
                });

            modelBuilder.Entity("Simpanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("JenisSimpananId")
                        .HasColumnType("int");

                    b.Property<string>("NomorRekening")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TanggalBuka")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JenisSimpananId");

                    b.HasIndex("NomorRekening")
                        .IsUnique();

                    b.HasIndex("PenggunaId");

                    b.ToTable("Simpanan");
                });

            modelBuilder.Entity("SimpananBerjangka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BungaDibayar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DiajukanPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DicairkanPada")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomorSertifikat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdukBerjangkaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TanggalJatuhTempo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TanggalMulai")
                        .HasColumnType("datetime2");

                    b.Property<int>("TenorBulan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NomorSertifikat")
                        .IsUnique();

                    b.HasIndex("PenggunaId");

                    b.HasIndex("ProdukBerjangkaId");

                    b.ToTable("SimpananBerjangka");
                });

            modelBuilder.Entity("TagihanWajib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DibuatPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiprosesPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("JatuhTempo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Periode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId", "Periode")
                        .IsUnique();

                    b.ToTable("TagihanWajib");
                });

            modelBuilder.Entity("TransaksiSukarela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Catatan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CatatanReview")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DiajukanPada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiprosesPada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jenis")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Nominal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PenggunaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PenggunaId", "Status");

                    b.ToTable("TransaksiSukarela");
                });

            modelBuilder.Entity("AngsuranPinjaman", b =>
                {
                    b.HasOne("Pinjaman", "Pinjaman")
                        .WithMany("Angsuran")
                        .HasForeignKey("PinjamanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pinjaman");
                });

            modelBuilder.Entity("EratOpsi", b =>
                {
                    b.HasOne("EratAgenda", "EratAgenda")
                        .WithMany("Opsi")
                        .HasForeignKey("EratAgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EratAgenda");
                });

            modelBuilder.Entity("EratSuara", b =>
                {
                    b.HasOne("EratAgenda", "EratAgenda")
                        .WithMany("Suara")
                        .HasForeignKey("EratAgendaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EratOpsi", "EratOpsi")
                        .WithMany("Suara")
                        .HasForeignKey("EratOpsiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EratAgenda");

                    b.Navigation("EratOpsi");

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("MutasiSimpanan", b =>
                {
                    b.HasOne("Simpanan", "Simpanan")
                        .WithMany("Mutasi")
                        .HasForeignKey("SimpananId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simpanan");
                });

            modelBuilder.Entity("PembayaranPinjaman", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pinjaman", "Pinjaman")
                        .WithMany()
                        .HasForeignKey("PinjamanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");

                    b.Navigation("Pinjaman");
                });

            modelBuilder.Entity("PengajuanPinjaman", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("Pinjaman", b =>
                {
                    b.HasOne("PengajuanPinjaman", "Pengajuan")
                        .WithOne("Pinjaman")
                        .HasForeignKey("Pinjaman", "PengajuanPinjamanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pengajuan");

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("PostingBungaSukarela", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("Simpanan", b =>
                {
                    b.HasOne("JenisSimpanan", "JenisSimpanan")
                        .WithMany("Simpanan")
                        .HasForeignKey("JenisSimpananId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JenisSimpanan");

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("SimpananBerjangka", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProdukBerjangka", "Produk")
                        .WithMany("SimpananBerjangka")
                        .HasForeignKey("ProdukBerjangkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pengguna");

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("TagihanWajib", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("TransaksiSukarela", b =>
                {
                    b.HasOne("Pengguna", "Pengguna")
                        .WithMany()
                        .HasForeignKey("PenggunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pengguna");
                });

            modelBuilder.Entity("EratAgenda", b =>
                {
                    b.Navigation("Opsi");

                    b.Navigation("Suara");
                });

            modelBuilder.Entity("EratOpsi", b =>
                {
                    b.Navigation("Suara");
                });

            modelBuilder.Entity("JenisSimpanan", b =>
                {
                    b.Navigation("Simpanan");
                });

            modelBuilder.Entity("PengajuanPinjaman", b =>
                {
                    b.Navigation("Pinjaman");
                });

            modelBuilder.Entity("Pinjaman", b =>
                {
                    b.Navigation("Angsuran");
                });

            modelBuilder.Entity("ProdukBerjangka", b =>
                {
                    b.Navigation("SimpananBerjangka");
                });

            modelBuilder.Entity("Simpanan", b =>
                {
                    b.Navigation("Mutasi");
                });
#pragma warning restore 612, 618
        }
    }
}
